version: '3.7'
x-othentic-cli: &othentic-cli
  env_file:
    - .env
  build:
    context: .
    dockerfile: ./Dockerfile
services:
  aggregator:
    <<: *othentic-cli
    command: ["node", "aggregator", "--json-rpc"]
    ports:
      - "8545:8545"
      - "9876:9876"
    networks:
      p2p:
        ipv4_address: 10.8.0.69
  attester-1:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.42",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_VALIDATOR1}
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.2
  attester-2:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.43",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_VALIDATOR2}
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.3
  attester-3:
    <<: *othentic-cli
    command: [
      "node",
      "attester",
      "/ip4/10.8.0.69/tcp/9876/p2p/${OTHENTIC_BOOTSTRAP_ID}",
      "--avs-webapi",
      "http://10.8.0.44",
    ]
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_VALIDATOR3}
    depends_on:
      aggregator:
        condition: service_started
    networks:
      p2p:
        ipv4_address: 10.8.0.4
  attester-1-avs:
    build:
      context: ./attester
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_VALIDATOR1}
      - NODE_RPC=http://10.8.0.69:8545/
    networks:
      p2p:
        ipv4_address: 10.8.0.42
  attester-2-avs:
    build:
      context: ./attester
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_VALIDATOR2}
      - NODE_RPC=http://10.8.0.69:8545/
    networks:
      p2p:
        ipv4_address: 10.8.0.43
  attester-3-avs:
    build:
      context: ./attester
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_VALIDATOR3}
      - NODE_RPC=http://10.8.0.69:8545/
    networks:
      p2p:
        ipv4_address: 10.8.0.44

networks:
  p2p:
    driver: bridge
    ipam:
     config:
       - subnet: 10.8.0.0/16
         gateway: 10.8.0.1
